# Generated by Django 4.0.2 on 2022-02-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('product_type', models.CharField(choices=[('tiles', 'Плочки'), ('laminat', 'Ламинат')], max_length=10)),
                ('series', models.CharField(max_length=50)),
                ('dimensions', models.CharField(max_length=10)),
                ('surface', models.CharField(choices=[], max_length=50)),
                ('qunatity_pack', models.FloatField()),
                ('area_pack', models.FloatField()),
                ('area_pallet', models.FloatField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
