# Generated by Django 4.0.2 on 2022-02-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='surface',
            field=models.CharField(choices=[('mat', 'Мат'), ('sjaj', 'Сјај')], max_length=50),
        ),
    ]
